version: '3'

services:
  cassandra:
    image: docker.io/bitnami/cassandra:latest
    container_name: cassandra
    ports:
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
#    healthcheck:
#      test: [ "CMD", "/opt/bitnami/cassandra/bin/cqlsh", "-u cassandra", "-p cassandra" ,"-e \"describe keyspaces\"" ]
#      interval: 15s
#      timeout: 10s
#      retries: 10
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra
    restart: always

  cassandra-load-keyspace:
    container_name: cassandra-load-keyspace
    image: docker.io/bitnami/cassandra:latest
    depends_on:
      - cassandra
    volumes:
      - ./cql-scripts/schema.cql:/schema.cql
    command: /bin/bash -c "sleep 30 && echo Creating cassandra keyspace && cqlsh cassandra -u cassandra -p cassandra -f /schema.cql"

volumes:
  cassandra_data:
    driver: local